server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: inst-photo-service
  datasource:
    url: jdbc:postgresql://postgres-photo:5432/photo
    username: postgres
    password: 1234
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 100KB
      max-file-size: 20MB
      max-request-size: 25MB
file:
  upload-dir: photo-storage\\

